// IDs are persisted as array indices. Append new choices to preserve saved invitations.
export const characterOptions = [
  {
    name: "Side-swept waves",
    skin: "#bb8060",
    hair: "#33272b",
    style: "waves",
  },
  {
    name: "Trimmed beard",
    skin: "#d29f7c",
    hair: "#33272b",
    style: "crop",
    beard: "short",
  },
  { name: "Long waves", skin: "#976548", hair: "#33272b", style: "waves" },
  {
    name: "Full beard",
    skin: "#e3b797",
    hair: "#33272b",
    style: "crop",
    beard: "full",
  },
  { name: "Elegant bun", skin: "#b57b59", hair: "#292329", style: "bun" },
  {
    name: "Curls & beard",
    skin: "#754d38",
    hair: "#252126",
    style: "curls",
    beard: "rounded",
  },
  { name: "Long braid", skin: "#d4a17a", hair: "#493129", style: "braid" },
  {
    name: "Quiff & beard",
    skin: "#9d6b4c",
    hair: "#30262a",
    style: "quiff",
    beard: "tapered",
  },
  { name: "Chin-length bob", skin: "#edc4a6", hair: "#54392f", style: "bob" },
  {
    name: "Bearded classic",
    skin: "#84583f",
    hair: "#292329",
    style: "beard",
    beard: "classic",
  },
] as const;

export const outfitOptions = [
  {
    name: "Draped silk",
    color: "#96364d",
    sangeet: "#824796",
    trim: "#d9b183",
    shape: "flared",
    detail: "drape",
  },
  {
    name: "Classic cream",
    color: "#f3deb5",
    sangeet: "#253c79",
    trim: "#b99c67",
    shape: "straight",
    detail: "buttons",
  },
  {
    name: "Garden formal",
    color: "#496554",
    sangeet: "#176e76",
    trim: "#bcaa79",
    shape: "straight",
    detail: "panels",
  },
  {
    name: "Rose lehenga",
    color: "#c77487",
    sangeet: "#ae497e",
    trim: "#f4d7b4",
    shape: "flared",
    detail: "floral",
  },
  {
    name: "Midnight sherwani",
    color: "#293b65",
    sangeet: "#354b91",
    trim: "#d6b574",
    shape: "straight",
    detail: "sash",
  },
  {
    name: "Saffron anarkali",
    color: "#dc9637",
    sangeet: "#bb692b",
    trim: "#fff0bd",
    shape: "flared",
    detail: "pleats",
  },
  {
    name: "Teal achkan",
    color: "#286e75",
    sangeet: "#195b69",
    trim: "#dfc18a",
    shape: "straight",
    detail: "buttons",
  },
  {
    name: "Lavender silk",
    color: "#9376ad",
    sangeet: "#654e96",
    trim: "#e9d9f0",
    shape: "flared",
    detail: "drape",
  },
  {
    name: "Ruby bandhgala",
    color: "#823549",
    sangeet: "#9c3863",
    trim: "#e1b986",
    shape: "straight",
    detail: "waistcoat",
  },
  {
    name: "Champagne festive",
    color: "#d7bb83",
    sangeet: "#a28351",
    trim: "#fff2cc",
    shape: "flared",
    detail: "tiers",
  },
] as const;

export const themeDescriptions = {
  royal: "A little grandeur. A lot of heart.",
  marigold: "Sunlit, spirited, full of warmth.",
  garden: "For a love that grows beautifully.",
  rose: "Soft petals and a little romance.",
  midnight: "A celebration beneath the stars.",
  lotus: "Serene waters, timeless beginnings.",
};

export const themeAccents = {
  royal: "#4a1728",
  marigold: "#793d2b",
  garden: "#315448",
  rose: "#843f59",
  midnight: "#283858",
  lotus: "#245d67",
};
