// Interface copy is separate from optional invitation translation assistance.
// A native Gujarati editorial review remains a launch requirement.
export const ownerGujarati: Record<string, string> = {
  Gender: "લિંગ",
  Male: "પુરુષ",
  Female: "સ્ત્રી",
  "The male partner arrives on horseback and the female partner waits. If both match, the second partner arrives.":
    "પુરુષ સાથી ઘોડા પર આવે છે અને સ્ત્રી સાથી રાહ જુએ છે. બંનેનું લિંગ સમાન હોય તો બીજા સાથી ઘોડા પર આવે છે.",
  "Your full six-month term starts at actual publication. Responses can be exported for another 30 days.":
    "તમારો છ મહિનાનો સમયગાળો આમંત્રણ પ્રકાશિત થાય ત્યારથી શરૂ થાય છે. ત્યાર પછીના ૩૦ દિવસ સુધી પ્રતિસાદ નિકાસ કરી શકાશે.",
  "Save domain": "ડોમેન સાચવો",
  "Keep current domain": "હાલનું ડોમેન રાખો",
  "Check again": "ફરી તપાસો",
  "Your domain is saved.": "તમારું ડોમેન સાચવાયું છે.",
  "This domain is available.": "આ ડોમેન ઉપલબ્ધ છે.",
  "Checking domain availability…": "ડોમેનની ઉપલબ્ધતા તપાસી રહ્યા છીએ…",
  "This domain name is reserved. Choose another.":
    "આ ડોમેન નામ અનામત છે. બીજું પસંદ કરો.",
  "That link is already taken. Choose another.":
    "આ લિંક પહેલેથી ઉપયોગમાં છે. બીજી પસંદ કરો.",
  "Use 3–63 lowercase letters, numbers, or single hyphens between words.":
    "૩–૬૩ અંગ્રેજી નાના અક્ષરો, અંકો અથવા શબ્દો વચ્ચે એક હાઇફન વાપરો.",
  "Could not check availability. Please try again.":
    "ઉપલબ્ધતા તપાસી શકાઈ નથી. ફરી પ્રયાસ કરો.",
  "Your domain was not saved. Check the save message above and try again.":
    "તમારું ડોમેન સાચવાયું નથી. ઉપરનો સંદેશ તપાસો અને ફરી પ્રયાસ કરો.",
  "You can change your domain before or after payment. Save your domain before continuing to checkout.":
    "તમે ચુકવણી પહેલાં કે પછી ડોમેન બદલી શકો છો. ચુકવણી તરફ આગળ વધતાં પહેલાં ડોમેન સાચવો.",
  "Saving a new domain changes your live link immediately. The old link will stop working; update shared links and download a new QR code.":
    "નવું ડોમેન સાચવતાં તમારી જાહેર લિંક તરત બદલાય છે. જૂની લિંક કામ કરવાનું બંધ કરશે; શેર કરેલી લિંક્સ બદલો અને નવો QR કોડ ડાઉનલોડ કરો.",
  "Shaadi morning": "લગ્નની સવાર",
  "Sitar serenade": "સિતારના સૂર",
  "Mehendi afternoon": "મહેંદીની બપોર",
  "Sangeet under the stars": "તારલાં નીચે સંગીત",
  "Preview music": "સંગીત સાંભળો",
  "Stop preview": "સંગીત બંધ કરો",
  "Music could not play. Please try again.":
    "સંગીત ચાલુ થઈ શક્યું નહીં. ફરી પ્રયત્ન કરો.",
  "Six original instrumental tracks. Guests choose when to turn sound on.":
    "છ મૌલિક વાદ્ય ધૂનો. મહેમાનો પોતાની ઇચ્છાથી સંગીત ચાલુ કરી શકે છે.",
  Invitations: "આમંત્રણો",
  "Live celebrations": "પ્રકાશિત ઉજવણીઓ",
  "Drafts to make your own": "અધૂરાં આમંત્રણો",
  "A little inspiration?": "થોડી પ્રેરણા જોઈએ?",
  "Explore six invitation styles, made for the way you celebrate.":
    "તમારી ઉજવણીને અનુરૂપ છ આમંત્રણ શૈલીઓ જુઓ.",
  "Secure checkout": "સુરક્ષિત ચુકવણી",
  "Together with our families": "અમારા પરિવાર સાથે",
  "All six invitation themes": "બધી છ આમંત્રણ થીમ",
  "English & Gujarati": "અંગ્રેજી અને ગુજરાતી",
  "Six original music tracks": "છ મૌલિક સંગીત ધૂનો",
  "Private RSVPs & guest export": "ખાનગી પ્રતિસાદ અને મહેમાનોની યાદી",
  "Shareable link & QR code": "શેર કરી શકાય તેવી લિંક અને QR કોડ",
  "Payments secured by Razorpay": "Razorpay દ્વારા સુરક્ષિત ચુકવણી",
  "Your guest book": "તમારા મહેમાનોની યાદી",
  "Every response, all in one place.": "બધા પ્રતિસાદ, એક જ જગ્યાએ.",
  "Celebration headcounts": "પ્રસંગ પ્રમાણે મહેમાનો",
  "Guest responses": "મહેમાનોના પ્રતિસાદ",
  families: "પરિવારો",
  responses: "પ્રતિસાદ",
  "Filter responses": "પ્રતિસાદ ફિલ્ટર કરો",
  "All responses": "બધા પ્રતિસાદ",
  "Updating responses…": "પ્રતિસાદ અપડેટ થઈ રહ્યા છે…",
  "Try another name or change the attendance filter.":
    "બીજું નામ શોધો અથવા હાજરીનું ફિલ્ટર બદલો.",
  "Browse 6 templates": "૬ તૈયાર લખાણ જુઓ",
  "Family line templates": "પરિવાર માટે તૈયાર લખાણ",
  "Invitation wording templates": "આમંત્રણ માટે તૈયાર લખાણ",
  "Choose a starting point. You can edit every word after applying it.":
    "શરૂઆત માટે લખાણ પસંદ કરો. પસંદ કર્યા પછી દરેક શબ્દ બદલી શકશો.",
  "Wording style": "લખાણની શૈલી",
  "Applying a template replaces the wording in the languages you choose.":
    "તૈયાર લખાણ પસંદ કરેલી ભાષાઓના હાલના લખાણને બદલે છે.",
  "Use English & Gujarati": "અંગ્રેજી અને ગુજરાતી વાપરો",
  "Use Gujarati only": "ફક્ત ગુજરાતી વાપરો",
  "Use English only": "ફક્ત અંગ્રેજી વાપરો",
  "Template applied. You can edit the wording.":
    "લખાણ ઉમેરાયું. તમે તેને બદલી શકશો.",
  "Translate missing Gujarati": "ખાલી ગુજરાતી લખાણનો અનુવાદ કરો",
  "Translate English into Gujarati": "અંગ્રેજીમાંથી ગુજરાતી અનુવાદ કરો",
  "Review your Gujarati translations": "ગુજરાતી અનુવાદ તપાસો",
  "Only empty Gujarati fields are filled. Review names, addresses, and wording before applying.":
    "ફક્ત ખાલી ગુજરાતી જગ્યાઓ ભરાશે. ઉમેરતાં પહેલાં નામ, સરનામાં અને લખાણ તપાસો.",
  "There are no empty Gujarati fields with English text to translate.":
    "અનુવાદ માટે અંગ્રેજી લખાણ ધરાવતી કોઈ ખાલી ગુજરાતી જગ્યા નથી.",
  "Selected English text is sent to MyMemory for translation. Its free daily limit applies. Ready templates work without the service.":
    "પસંદ કરેલું અંગ્રેજી લખાણ અનુવાદ માટે MyMemory ને મોકલાશે. તેની મફત દૈનિક મર્યાદા લાગુ પડે છે. તૈયાર લખાણ માટે આ સેવા જરૂરી નથી.",
  "English characters selected": "અંગ્રેજી અક્ષરો પસંદ કર્યા",
  "Select fewer fields to continue.": "આગળ વધવા ઓછી જગ્યાઓ પસંદ કરો.",
  "Translating…": "અનુવાદ થઈ રહ્યો છે…",
  "Translate selected fields": "પસંદ કરેલા લખાણનો અનુવાદ કરો",
  "Apply reviewed translations": "તપાસેલા અનુવાદ ઉમેરો",
  "Choose fields again": "લખાણ ફરી પસંદ કરો",
  "Shorten this translation before applying.":
    "ઉમેરતાં પહેલાં આ અનુવાદ ટૂંકો કરો.",
  "Gujarati translations applied. You can edit them below.":
    "ગુજરાતી અનુવાદ ઉમેરાયા. નીચે તેમને બદલી શકશો.",
  "Translation failed. Please try again.":
    "અનુવાદ થઈ શક્યો નથી. ફરી પ્રયત્ન કરો.",
  "Translation timed out. Please try again.":
    "અનુવાદ માટેનો સમય પૂરો થયો. ફરી પ્રયત્ન કરો.",
  "Translation service is unavailable. Please try again.":
    "અનુવાદ સેવા ઉપલબ્ધ નથી. ફરી પ્રયત્ન કરો.",
  "No Gujarati translation was returned. Please enter this field yourself.":
    "ગુજરાતી અનુવાદ મળ્યો નથી. આ લખાણ જાતે ઉમેરો.",
  "This text could not be translated. Try a shorter sentence or write the Gujarati yourself.":
    "આ લખાણનો અનુવાદ થયો નથી. ટૂંકું વાક્ય વાપરો અથવા ગુજરાતી જાતે લખો.",
  "The translation service’s daily limit has been reached. Try again tomorrow or use a template.":
    "અનુવાદ સેવાની દૈનિક મર્યાદા પૂરી થઈ છે. આવતીકાલે પ્રયત્ન કરો અથવા તૈયાર લખાણ વાપરો.",
  "Mothers’ names": "માતાઓનાં નામ",
  "Partner 1’s name": "સાથી ૧નું નામ",
  "Partner 2’s name": "સાથી ૨નું નામ",
  "Partner 1’s mother’s name": "સાથી ૧નાં માતાનું નામ",
  "Partner 2’s mother’s name": "સાથી ૨નાં માતાનું નામ",
  "Add each partner’s mother’s name. These appear with the family’s blessings on your invitation.":
    "બંને સાથીનાં માતાનાં નામ ઉમેરો. આમંત્રણમાં પરિવારના આશીર્વાદ સાથે આ નામ દેખાશે.",
  "Translate from English, use bilingual templates, or write your own Gujarati. Missing translations use the default language.":
    "અંગ્રેજીમાંથી અનુવાદ કરો, બંને ભાષામાં તૈયાર લખાણ વાપરો અથવા ગુજરાતી જાતે લખો. અનુવાદ ન હોય ત્યાં મૂળ ભાષાનું લખાણ દેખાશે.",
  "Suggested functions": "સૂચિત પ્રસંગો",
  "Choose a function to add its name in both languages. Add your dates and venue next.":
    "બંને ભાષામાં નામ ઉમેરવા પ્રસંગ પસંદ કરો. પછી તારીખ અને સ્થળ ઉમેરો.",
  Function: "પ્રસંગ",
  "Event notes": "પ્રસંગની નોંધ",
  "Use venue from an earlier function": "અગાઉના પ્રસંગનું સ્થળ વાપરો",
  "Choose an earlier function": "અગાઉનો પ્રસંગ પસંદ કરો",
  "Copies venue, address, and directions in both languages. You can edit this function’s location afterwards.":
    "સ્થળ, સરનામું અને રસ્તાની લિંક બંને ભાષામાં ઉમેરાશે. પછી આ પ્રસંગનું સ્થળ બદલી શકશો.",
  "Venue, address, and directions copied in both languages.":
    "સ્થળ, સરનામું અને રસ્તાની લિંક બંને ભાષામાં ઉમેરાયાં.",
  "Use our names": "અમારાં નામ વાપરો",
  "Offer Gujarati to guests": "મહેમાનો માટે ગુજરાતી ઉમેરો",
  "Your invitation link:": "તમારી આમંત્રણ લિંક:",
  Couple: "યુગલ",
  Functions: "પ્રસંગો",
  Appearance: "દેખાવ",
  Review: "સમીક્ષા",
  "Back to invitations": "આમંત્રણો પર પાછા જાઓ",
  "Your name": "તમારું નામ",
  Preview: "પૂર્વાવલોકન",
  "Invitation setup": "આમંત્રણની ગોઠવણી",
  "Your latest changes are not saved": "તમારા છેલ્લા ફેરફારો સાચવાયા નથી",
  "Review saved version": "સાચવેલી આવૃત્તિ જુઓ",
  "Retry saving": "ફરી સાચવો",
  Saved: "સાચવ્યું",
  "Saving…": "સાચવી રહ્યું છે…",
  "Unsaved changes": "વણસાચવેલા ફેરફારો",
  "Not saved": "સાચવાયું નથી",
  Conflict: "આવૃત્તિઓમાં તફાવત",
  "The two of you.": "તમે બંને.",
  "Every celebration.": "દરેક ઉજવણી.",
  "Make it feel like you.": "તમારી પસંદગીનો રંગ આપો.",
  "One last look.": "એક અંતિમ નજર.",
  "The names, the people, and the words that make this yours.":
    "તમારા નામ, પરિવાર અને હૃદયના શબ્દો.",
  "From an intimate gathering to the big day. Add up to ten events.":
    "નાનકડા મેળાવડાથી લગ્નના દિવસ સુધી. વધુમાં વધુ દસ પ્રસંગ ઉમેરો.",
  "Choose an illustrated world and add your personal touches.":
    "ચિત્રિત થીમ પસંદ કરો અને તેને તમારો સ્પર્શ આપો.",
  "Your changes are private until you publish. Check the details before sharing.":
    "પ્રકાશિત કરો ત્યાં સુધી ફેરફારો ખાનગી રહેશે. શેર કરતાં પહેલાં વિગતો તપાસો.",
  "Content language": "લખાણની ભાષા",
  English: "English",
  Gujarati: "ગુજરાતી",
  Partner: "સાથી",
  "’s name": "નું નામ",
  "Family line": "પરિવારનું નામ",
  "Your welcome message": "તમારો સ્વાગત સંદેશ",
  "Invitation wording": "આમંત્રણનું લખાણ",
  "Guest languages": "મહેમાનો માટેની ભાષાઓ",
  "Write each translation yourself. Missing translations use the default language.":
    "દરેક ભાષાનું લખાણ જાતે લખો. અનુવાદ ન હોય ત્યાં મૂળ ભાષાનું લખાણ દેખાશે.",
  "Default language": "મૂળ ભાષા",
  "Host contacts": "યજમાનના સંપર્ક",
  Optional: "વૈકલ્પિક",
  "Host name": "યજમાનનું નામ",
  Phone: "ફોન",
  "Show this contact publicly to anyone with the link":
    "લિંક ધરાવનાર દરેકને આ સંપર્ક બતાવો",
  "Remove contact": "સંપર્ક દૂર કરો",
  "Add host contact": "યજમાનનો સંપર્ક ઉમેરો",
  Archived: "સંગ્રહિત",
  "Move event up": "પ્રસંગ ઉપર ખસેડો",
  "Move event down": "પ્રસંગ નીચે ખસેડો",
  "Event title": "પ્રસંગનું નામ",
  "Starts · Asia/Kolkata": "શરૂઆત · ભારતીય સમય",
  "Ends · optional": "સમાપ્તિ · વૈકલ્પિક",
  "This event is in the past. You can still correct its details.":
    "આ પ્રસંગની તારીખ વીતી ગઈ છે. તમે તેની વિગતો સુધારી શકો છો.",
  "Venue name": "સ્થળનું નામ",
  Address: "સરનામું",
  "Event notes · optional": "પ્રસંગની નોંધ · વૈકલ્પિક",
  "Directions link · optional": "રસ્તાની લિંક · વૈકલ્પિક",
  "Main wedding event": "મુખ્ય લગ્ન પ્રસંગ",
  "Make main event": "મુખ્ય પ્રસંગ બનાવો",
  "Restore event": "પ્રસંગ પાછો લાવો",
  "Archive event": "પ્રસંગ સંગ્રહિત કરો",
  "New celebration": "નવો પ્રસંગ",
  "Add celebration": "પ્રસંગ ઉમેરો",
  "Archiving hides an event from future invitations. Historical responses stay available.":
    "સંગ્રહિત પ્રસંગ નવા આમંત્રણમાં નહીં દેખાય. અગાઉના પ્રતિસાદ ઉપલબ્ધ રહેશે.",
  "Your invitation theme": "તમારા આમંત્રણની થીમ",
  "Royal Maroon": "શાહી મરૂન",
  Marigold: "ગલગોટા",
  "Garden Ivory": "બગીચાની આઇવરી",
  "Rose Blush": "ગુલાબી રંગત",
  "Midnight Sapphire": "મધરાતનો નીલમ",
  "Lotus Lagoon": "કમળનું સરોવર",
  "Character appearance": "પાત્રનો દેખાવ",
  Clothes: "પોશાક",
  "Side-swept waves": "બાજુએ વાળેલા લહેરિયા વાળ",
  "Trimmed beard": "ટૂંકી દાઢી",
  "Long waves": "લાંબા લહેરિયા વાળ",
  "Full beard": "ભરાવદાર દાઢી",
  "Elegant bun": "સુંદર અંબોડો",
  "Curls & beard": "વાંકડિયા વાળ અને દાઢી",
  "Long braid": "લાંબી ચોટલી",
  "Quiff & beard": "ઊંચા વાળ અને દાઢી",
  "Chin-length bob": "હડપચી સુધીના વાળ",
  "Bearded classic": "દાઢીવાળો દેખાવ",
  "Rose lehenga": "ગુલાબી લહેંગો",
  "Midnight sherwani": "ઘેરી વાદળી શેરવાની",
  "Saffron anarkali": "કેસરી અનારકલી",
  "Teal achkan": "મોરપીંછ અચકન",
  "Lavender silk": "જાંબલી રેશમ",
  "Ruby bandhgala": "માણેક રંગનો બંધગળો",
  "Champagne festive": "સોનેરી ઉત્સવી પોશાક",
  "’s character": "નું પાત્ર",
  "Draped silk": "રેશમી પોશાક",
  "Classic cream": "ક્રીમ રંગનો પોશાક",
  "Garden formal": "બગીચાનો પોશાક",
  Music: "સંગીત",
  "No music": "સંગીત વિના",
  "Courtyard melody": "આંગણાની ધૂન",
  "Garden at dusk": "સાંજનો બગીચો",
  "Original instrumental miniatures. Guests choose when to turn sound on.":
    "મૂળ વાદ્યસંગીત. મહેમાનો ઇચ્છે ત્યારે અવાજ ચાલુ કરી શકે છે.",
  "Your photos ·": "તમારા ફોટા ·",
  "Uploading and preparing your photo…": "તમારો ફોટો અપલોડ થઈ રહ્યો છે…",
  "Up to five photos. JPEG, PNG, or WebP, under 10 MB each.":
    "વધુમાં વધુ પાંચ ફોટા. JPEG, PNG અથવા WebP; દરેક 10 MB કરતાં નાનો.",
  Remove: "દૂર કરો",
  "No completed photos to recover.": "પાછા લાવવા માટે તૈયાર ફોટા નથી.",
  "Recover completed uploads": "તૈયાર અપલોડ પાછા લાવો",
  "Photo added": "ફોટો ઉમેરાયો",
  "Choose a JPEG, PNG, or WebP photo under 10 MB.":
    "10 MB કરતાં નાનો JPEG, PNG અથવા WebP ફોટો પસંદ કરો.",
  "Photo upload failed. Your draft is safe; please retry.":
    "ફોટો અપલોડ ન થયો. તમારો ડ્રાફ્ટ સુરક્ષિત છે; ફરી પ્રયાસ કરો.",
  "This photo was rejected.": "આ ફોટો સ્વીકારાયો નથી.",
  "Your photo is still processing. Reopen Appearance in a moment to recover it.":
    "ફોટો તૈયાર થઈ રહ્યો છે. થોડી વાર પછી દેખાવ વિભાગમાં પાછો મેળવો.",
  "Your invitation link": "તમારા આમંત્રણની લિંક",
  "· Your link locks at first checkout.":
    "· પ્રથમ ચેકઆઉટ પછી લિંક બદલી શકાશે નહીં.",
  "A few details still need you": "થોડી વિગતો બાકી છે",
  "Ready for your final preview": "અંતિમ પૂર્વાવલોકન માટે તૈયાર",
  "celebrations ·": "પ્રસંગો ·",
  "No photos added. Your invitation will use the original illustrated couple.":
    "ફોટા ઉમેર્યા નથી. આમંત્રણમાં ચિત્રિત યુગલ દેખાશે.",
  "Untranslated names or event details use your default language. Review both languages in the preview.":
    "અનુવાદ ન હોય તેવા નામ અને વિગતો મૂળ ભાષામાં દેખાશે. પૂર્વાવલોકનમાં બંને ભાષાઓ તપાસો.",
  "Your invitation will be public by link": "લિંક ધરાવનાર આમંત્રણ જોઈ શકશે",
  "Anyone with the link can see published names, photos, venues, and contacts you marked public. Guest responses stay private.":
    "લિંક ધરાવનાર પ્રકાશિત નામ, ફોટા, સ્થળ અને જાહેર કરેલા સંપર્ક જોઈ શકશે. મહેમાનોના પ્રતિસાદ ખાનગી રહેશે.",
  "Preview the complete invitation": "સંપૂર્ણ આમંત્રણ જુઓ",
  "Your invitation updates are published": "આમંત્રણના ફેરફારો પ્રકાશિત થયા",
  "Preparing…": "તૈયાર થઈ રહ્યું છે…",
  "Publish updates": "ફેરફારો પ્રકાશિત કરો",
  "Continue to checkout": "ચુકવણી તરફ આગળ વધો",
  "Six calendar months of hosting begin when your first payment is verified and your invitation is published.":
    "પ્રથમ ચુકવણીની ચકાસણી અને આમંત્રણના પ્રકાશનથી છ કેલેન્ડર મહિનાનું હોસ્ટિંગ શરૂ થાય છે.",
  Back: "પાછા",
  Continue: "આગળ વધો",
  "Your guest’s first impression · live preview":
    "તમારા મહેમાનની પ્રથમ ઝલક · પૂર્વાવલોકન",
  "Live invitation preview": "આમંત્રણનું પૂર્વાવલોકન",
  "Changes appear here as you type. Only you can see this.":
    "લખતાં જ ફેરફારો અહીં દેખાશે. આ ફક્ત તમે જોઈ શકો છો.",
  "Your private preview": "તમારું ખાનગી પૂર્વાવલોકન",
  "This is how your guests will see the invitation. Responses are disabled.":
    "મહેમાનોને આમંત્રણ આ રીતે દેખાશે. અહીં પ્રતિસાદ મોકલી શકાશે નહીં.",
  "Full invitation preview": "સંપૂર્ણ આમંત્રણનું પૂર્વાવલોકન",
  "Review the newer saved draft": "નવો સાચવેલો ડ્રાફ્ટ તપાસો",
  "Your current edits have been kept. Choose which version to continue with.":
    "તમારા હાલના ફેરફારો રાખ્યા છે. કઈ આવૃત્તિ સાથે આગળ વધવું તે પસંદ કરો.",
  "Saved version": "સાચવેલી આવૃત્તિ",
  Unnamed: "નામ વિનાનું",
  "events.": "પ્રસંગો.",
  "Open the saved version for review": "સાચવેલી આવૃત્તિ તપાસવા ખોલો",
  "Use the saved version": "સાચવેલી આવૃત્તિ વાપરો",
  "Replace saved draft with my edits": "મારા ફેરફારોથી સાચવેલો ડ્રાફ્ટ બદલો",
  "Creating your draft…": "તમારો ડ્રાફ્ટ બની રહ્યો છે…",
  "Create an invitation": "આમંત્રણ બનાવો",
  "Sign out": "સાઇન આઉટ",
  "My invitations": "મારા આમંત્રણો",
  "Check your inbox.": "તમારું ઇનબોક્સ તપાસો.",
  "Your story starts here.": "તમારી વાર્તા અહીંથી શરૂ થાય છે.",
  "If this address can receive email, a sign-in link is on its way. It expires in 10 minutes.":
    "આ સરનામે ઈમેઇલ મળી શકતો હશે તો સાઇન-ઇન લિંક મોકલાશે. તે 10 મિનિટ સુધી માન્ય રહેશે.",
  "Create an invitation that feels like you. Sign in with an email link — no password to remember.":
    "તમારી પસંદગીનું આમંત્રણ બનાવો. ઈમેઇલ લિંકથી સાઇન ઇન કરો; પાસવર્ડ યાદ રાખવાની જરૂર નથી.",
  "Email address": "ઈમેઇલ સરનામું",
  "Your drafts and guest responses stay private.":
    "તમારા ડ્રાફ્ટ અને મહેમાનોના પ્રતિસાદ ખાનગી રહે છે.",
  "Could not send link": "લિંક મોકલી શકાઈ નથી",
  "Sending your link…": "લિંક મોકલાઈ રહી છે…",
  "Resend sign-in link": "સાઇન-ઇન લિંક ફરી મોકલો",
  "Email me a sign-in link": "મને સાઇન-ઇન લિંક મોકલો",
  "Local development inbox": "સ્થાનિક વિકાસ ઇનબોક્સ",
  "Your email is saved in the private .local/mail folder on this computer. No email was sent externally.":
    "તમારો ઈમેઇલ આ કમ્પ્યુટરના ખાનગી .local/mail ફોલ્ડરમાં સાચવ્યો છે. બહાર ઈમેઇલ મોકલાયો નથી.",
  "By continuing, you agree to the": "આગળ વધીને તમે સ્વીકારો છો:",
  terms: "શરતો",
  and: "અને",
  "privacy policy": "ગોપનીયતા નીતિ",
  "Just looking? Explore the demo": "પહેલાં ડેમો જુઓ",
  "Welcome back.": "ફરી સ્વાગત છે.",
  "Confirm below to open your private wedding workspace.":
    "તમારું ખાનગી કાર્યસ્થળ ખોલવા નીચે પુષ્ટિ કરો.",
  "This link cannot be used": "આ લિંક વાપરી શકાશે નહીં",
  "Request a fresh link.": "નવી લિંક મેળવો.",
  "It may have expired or already been used.":
    "લિંકની સમયમર્યાદા પૂરી થઈ હશે અથવા તે વપરાઈ ગઈ હશે.",
  "Sign-in failed.": "સાઇન-ઇન થયું નથી.",
  "Opening your workspace…": "તમારું કાર્યસ્થળ ખુલી રહ્યું છે…",
  "Continue to my invitations": "મારા આમંત્રણો પર જાઓ",
  "Back to your invitation": "આમંત્રણ પર પાછા જાઓ",
  "Let the joy travel.": "ખુશીઓ વહેંચો.",
  "Ready to invite your world?": "તમારા સ્વજનોને આમંત્રવા તૈયાર?",
  "Your invitation is published": "તમારું આમંત્રણ પ્રકાશિત થયું",
  "Share your link and welcome your first responses.":
    "તમારી લિંક શેર કરો અને પ્રતિસાદ મેળવો.",
  "Hosting ends": "હોસ્ટિંગ સમાપ્ત થશે",
  "(Asia/Kolkata). Export responses before":
    "(ભારતીય સમય). આ પહેલાં પ્રતિસાદ નિકાસ કરો",
  "Public invitation": "જાહેર આમંત્રણ",
  "View guest responses": "મહેમાનોના પ્રતિસાદ જુઓ",
  "One-time total · six calendar months of hosting":
    "એક વખતની કુલ ચુકવણી · છ કેલેન્ડર મહિનાનું હોસ્ટિંગ",
  "Your reviewed invitation, all celebrations, English and Gujarati, private RSVPs, and a downloadable QR code.":
    "તમારું આમંત્રણ, બધા પ્રસંગો, અંગ્રેજી અને ગુજરાતી, ખાનગી પ્રતિસાદ અને ડાઉનલોડ કરી શકાય તેવો QR કોડ.",
  "Expected hosting end if published today:":
    "આજે પ્રકાશિત કરો તો હોસ્ટિંગની અંદાજિત સમાપ્તિ:",
  "(Asia/Kolkata). Your full six-month term starts at actual publication. Responses can be exported for another 30 days.":
    "(ભારતીય સમય). છ મહિનાની મુદત પ્રકાશનથી શરૂ થશે. ત્યારબાદ 30 દિવસ સુધી પ્રતિસાદ નિકાસ કરી શકશો.",
  "An event falls after the hosting period": "એક પ્રસંગ હોસ્ટિંગની મુદત પછી છે",
  "Your invitation will expire before that event. Consider publishing closer to the wedding. Renewals are not included.":
    "તે પ્રસંગ પહેલાં આમંત્રણની મુદત પૂરી થશે. લગ્નની નજીક પ્રકાશિત કરવાનું વિચારો. નવીનીકરણ સામેલ નથી.",
  "Local test checkout": "સ્થાનિક પરીક્ષણ ચુકવણી",
  "No money will be charged. This tests the local order, publication, and response flow.":
    "કોઈ રકમ કપાશે નહીં. આ સ્થાનિક ઓર્ડર, પ્રકાશન અને પ્રતિસાદનું પરીક્ષણ છે.",
  "Payment needs support review": "ચુકવણી માટે સહાયની સમીક્ષા જરૂરી છે",
  "Paid — publishing in progress": "ચુકવણી થઈ — પ્રકાશન ચાલુ છે",
  "Confirming your reserved order": "તમારા અનામત ઓર્ડરની પુષ્ટિ થઈ રહી છે",
  "Your reviewed invitation is reserved": "તમારું તપાસેલું આમંત્રણ અનામત છે",
  "Your payment is recorded. We will keep retrying publication; you do not need to pay again.":
    "ચુકવણી નોંધાઈ છે. પ્રકાશનનો ફરી પ્રયાસ થશે; ફરી ચુકવણી કરવાની જરૂર નથી.",
  "This checkout uses the version saved when the order was first created. Later draft changes can be published after your invitation is live.":
    "આ ચુકવણી પ્રથમ ઓર્ડર વખતે સાચવેલી આવૃત્તિ માટે છે. આમંત્રણ પ્રકાશિત થયા પછી નવા ફેરફારો પ્રકાશિત કરી શકશો.",
  "I reviewed the invitation and understand the hosting term and public-link visibility.":
    "મેં આમંત્રણ તપાસ્યું છે અને હોસ્ટિંગની મુદત તથા જાહેર લિંક વિશે સમજું છું.",
  "By publishing you agree to the": "પ્રકાશિત કરીને તમે સ્વીકારો છો:",
  "terms and refund process": "શરતો અને રિફંડ પ્રક્રિયા",
  ". Your link will be /w/": ". તમારી લિંક હશે /w/",
  "Checkout update": "ચુકવણીની માહિતી",
  "Checking your order…": "ઓર્ડર તપાસાઈ રહ્યો છે…",
  "Check publication status": "પ્રકાશનની સ્થિતિ તપાસો",
  "Complete local test payment": "સ્થાનિક પરીક્ષણ ચુકવણી પૂર્ણ કરો",
  "Check payment status": "ચુકવણીની સ્થિતિ તપાસો",
  "Need help with your payment?": "ચુકવણી માટે મદદ જોઈએ છે?",
  "Your invitations": "તમારા આમંત્રણો",
  "The people who make it.": "તમારા પ્રસંગના સ્વજનો.",
  "· Guest responses": "· મહેમાનોના પ્રતિસાદ",
  "Export CSV": "CSV નિકાસ કરો",
  Responses: "પ્રતિસાદ",
  "Attending families": "આવનાર પરિવારો",
  Declines: "નહીં આવનાર",
  "Approximate visits": "અંદાજિત મુલાકાતો",
  "Confirmed people by event": "પ્રસંગ પ્રમાણે આવનાર લોકો",
  "People are counted separately for each event. These totals are not a unique guest count. Visits are approximate and may include repeat opens.":
    "દરેક પ્રસંગ માટે લોકોની અલગ ગણતરી થાય છે. આ કુલ અનન્ય મહેમાનોની સંખ્યા નથી. મુલાકાતો અંદાજિત છે અને વારંવાર ખોલેલી લિંક સામેલ હોઈ શકે છે.",
  "Search families": "પરિવાર શોધો",
  "Find a family…": "પરિવાર શોધો…",
  "Refresh responses": "પ્રતિસાદ ફરી લોડ કરો",
  "Could not refresh responses": "પ્રતિસાદ ફરી લોડ ન થયા",
  "Family / group": "પરિવાર / સમૂહ",
  Status: "સ્થિતિ",
  Note: "નોંધ",
  Actions: "ક્રિયાઓ",
  Attending: "આવશે",
  Declined: "નહીં આવે",
  "No response": "પ્રતિસાદ નથી",
  Previous: "પાછલું",
  Page: "પાનું",
  of: "માંથી",
  Next: "આગળ",
  "No matching families": "મેળ ખાતો પરિવાર નથી",
  "Good company is on its way.": "સ્વજનોના પ્રતિસાદની રાહ છે.",
  "Try another name or clear your search.": "બીજું નામ શોધો અથવા શોધ સાફ કરો.",
  "Share your invitation. Your first guest response will appear here.":
    "આમંત્રણ શેર કરો. પહેલો પ્રતિસાદ અહીં દેખાશે.",
  "Delete this response?": "આ પ્રતિસાદ કાઢી નાખવો છે?",
  "This removes the family’s response and its event counts. Their private edit link will stop working. This cannot be undone.":
    "આ પરિવારનો પ્રતિસાદ અને તેની સંખ્યા દૂર થશે. તેમની ખાનગી ફેરફાર લિંક કામ નહીં કરે. આ ક્રિયા પાછી ફેરવી શકાશે નહીં.",
  "Keep response": "પ્રતિસાદ રાખો",
  "Response deleted": "પ્રતિસાદ કાઢી નાખ્યો",
  "Deleting…": "કાઢી રહ્યું છે…",
  "Delete response": "પ્રતિસાદ કાઢી નાખો",
  "Your celebrations.": "તમારી ઉજવણીઓ.",
  "A place for every detail, from the first draft to the final RSVP.":
    "પ્રથમ ડ્રાફ્ટથી અંતિમ પ્રતિસાદ સુધી, દરેક વિગત માટે એક સ્થળ.",
  "Your next chapter, beautifully invited.":
    "તમારા નવા અધ્યાયનું સુંદર આમંત્રણ.",
  "Create your first invitation. Explore every theme and preview your story before you pay.":
    "પ્રથમ આમંત્રણ બનાવો. ચુકવણી પહેલાં દરેક થીમ અને તમારી વાર્તા જુઓ.",
  "Explore a finished invitation": "તૈયાર આમંત્રણ જુઓ",
  Expired: "મુદત પૂરી",
  Published: "પ્રકાશિત",
  Draft: "ડ્રાફ્ટ",
  "Your private invitation in the making":
    "તમારું ખાનગી આમંત્રણ તૈયાર થઈ રહ્યું છે",
  "Export responses before": "આ પહેલાં પ્રતિસાદ નિકાસ કરો",
  "Edit invitation": "આમંત્રણમાં ફેરફાર કરો",
  "Continue creating": "બનાવવાનું ચાલુ રાખો",
  "View invitation": "આમંત્રણ જુઓ",
};
